<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find lecxacro)/urdf/variables.xacro"/>
  <material name="green">
    <color rgba="0 1 0 0.5"/>
  </material>

  <link name="base">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}"
                  length="${base_length}"/>
      </geometry>
      <origin rpy="0 0 0"
              xyz="0 0 ${base_length/2}"/>
    </visual>
  </link>

  <link name="link1">
    <visual>
      <geometry>
        <cylinder radius="${link1_radius}"
                  length="${link1_length}"/>
      </geometry>
      <origin rpy="0 0 0"
              xyz="0 0 ${link1_length/2}"/>
      <material name="green"/>
    </visual>
  </link>

  <link name="link2">
    <visual>
      <geometry>
        <box size="1 0.1 0.1"/>
      </geometry>
      <origin rpy="0 0 0"
              xyz="0 0 0.05"/>
      <material name="green"/>
    </visual>
  </link>

  <joint name="j1" type="revolute">
    <parent link="base"/>
    <child  link="link1"/>
    <origin xyz="0 0 ${base_length}"/>
    <axis   xyz="1 0 0"/>
    <limit  effort="10"
            velocity="1"
            lower="-1.57"
            upper="1.57"/>
  </joint>

  <joint name="j2" type="prismatic">
    <parent link="link1"/>
    <child  link="link2"/>
    <origin xyz="0 0 ${link1_length}"/>
    <axis   xyz="1 0 0"/>
    <limit  effort="10"
            velocity="1"
            lower="-0.5"
            upper="0.5"/>
  </joint>
</robot>

